### ISSUE TITLE
Error starting the GUI example

### ISSUE THREAD

**Issue by hesolium** [trieschlab/SORNSim#3]
After installation by 'pip install ...'.
Running the example (User Interface) provided in the readme file ends with an error.

/usr/bin/python3.8 /home/heniek/snn/pymo/gui.py
set network size to 10 x 10
clear
Initialize: <PymoNNto.Exploration.Network_UI.Basic_Tabs.sidebar_neuron_grid.UI_sidebar_neuron_grid_module object at 0x7f35067ea730>
Initialize: <PymoNNto.Exploration.Network_UI.Basic_Tabs.multi_group_plot_tab.multi_group_plot_tab object at 0x7f34ffa60a90>
Initialize: <PymoNNto.Exploration.Network_UI.Basic_Tabs.spiketrain_tab.spiketrain_tab object at 0x7f34ffa60b50>
Initialize: <PymoNNto.Exploration.Network_UI.Basic_Tabs.weight_tab.weight_tab object at 0x7f34ffa60a30>
Initialize: <PymoNNto.Exploration.Network_UI.Basic_Tabs.partition_tab.partition_tab object at 0x7f34fb063520>
Initialize: <PymoNNto.Exploration.Network_UI.Basic_Tabs.PCA_tab.PCA_tab object at 0x7f34fb063640>
Initialize: <PymoNNto.Exploration.Network_UI.Basic_Tabs.isi_tab.isi_tab object at 0x7f34fb063670>
Initialize: <PymoNNto.Exploration.Network_UI.Basic_Tabs.hist_tab.hist_tab object at 0x7f34fb0636a0>
Initialize: <PymoNNto.Exploration.Network_UI.Basic_Tabs.single_group_plot_tab.single_group_plot_tab object at 0x7f34fb0636d0>
Initialize: <PymoNNto.Exploration.Network_UI.Basic_Tabs.stability_tab.stability_tab object at 0x7f34fb063700>
Initialize: <PymoNNto.Exploration.Network_UI.Basic_Tabs.fourier_tab.fourier_tab object at 0x7f34fb0637f0>
Initialize: <PymoNNto.Exploration.Network_UI.Basic_Tabs.Analysis_Module_tab.Analysis_Module_tab object at 0x7f34fb0638b0>
[<PymoNNto.Exploration.Network_UI.Neuron_Classification_Colorizer.Neuron_Classification_Colorizer object at 0x7f34fb063be0>]
Traceback (most recent call last):
  File "/home/heniek/snn/pymo/gui.py", line 42, in <module>
    Network_UI(My_Network, modules=my_UI_modules, label='My_Network_UI', group_display_count=1).show()
  File "/usr/local/lib/python3.8/dist-packages/PymoNNto/Exploration/Network_UI/Network_UI.py", line 87, in __init__
    module.initialize(self)
  File "/usr/local/lib/python3.8/dist-packages/PymoNNto/Exploration/Network_UI/Basic_Tabs/Analysis_Module_tab.py", line 70, in initialize
    caption = Network_UI.Add_element(QLabel(obj.tags[0]))
IndexError: list index out of range

Process finished with exit code 1
----------------------------------------------------------------------------------------------------------------------------------
Source code:
[
    def initialize(self, Network_UI):
        self.a_module_tab = Network_UI.Next_Tab(self.title)

        print(Network_UI.network.NeuronGroups[0].analysis_modules)

        for obj in [Network_UI.network]+Network_UI.network.NeuronGroups:#Network_UI.network.all_objects()
Error -->            caption = Network_UI.Add_element(QLabel(obj.tags[0]))
            font = QFont('SansSerif', 16)
            font.setUnderline(True)

]

**Comment by gitmv** [comment]
Thanks for your comment.

There was a small bug in a new ui tab in version 1.0.4.
The bug should be fixed now.
You can eighter
- update to the new version 1.0.5 
- or you can solve the issue by giving the network object a tag with My_Network=Network(... , tag='my_network')
- or you can comment out the Analysis_Module_tab in the get_default_UI_modules function.

Greetings
Marius
