### ISSUE TITLE
docs: typo in Refractory period

### ISSUE THREAD

**Issue by realamirhe** [trieschlab/SORNSim#4]
In the [documentation code](https://github.com/trieschlab/PymoNNto/blob/939244cbee53a9a5010fa40f17e164ae093c25c2/docs/Behaviours/Refractory_Period.md) 

It seems that the neuron refractory counter named as `refractory_counter_analog` but used as `refractory_counter`

```diff
class refractory(Behaviour):
    def set_variables(self, neurons):
-       neurons.refractory_counter_analog = neurons.get_neuron_vec()
+       neurons.refractory_counter = neurons.get_neuron_vec()
```

**Comment by gitmv** [comment]
Thank you! 
The typo is fixed now.
