### ISSUE TITLE
Wrong copyright holder

### ISSUE THREAD

**Issue by saeedark** [trieschlab/SORNSim#8]
https://github.com/trieschlab/PymoNNto/blob/26941a53f445e411f27af75df615d40876d25022/LICENSE#L3

The string after year should refer to the copyright holder which I think is "Trieschlab".

**Comment by gitmv** [comment]
Im am very sorry, i wanted to add it so that it is more clear that ist falls under the MIT license, because you asked for it. I saw that you have added this LICENSE file so that "MIT" appears under the about section. I totally forgot to change it. Thank you very much!
